# twitter-clone/Dockerfile

# Stage 1: Install dependencies
FROM node:18-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
# Use npm ci for faster, more reliable installs based on lockfile
RUN npm ci

# Stage 2: Build the application
FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set NODE_ENV to production for Next.js build optimizations
ENV NODE_ENV production

# --- Optional: Pass build-time environment variables ---
# Replace with your actual build-time variables if needed
# ARG NEXT_PUBLIC_API_URL
# ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
# ARG NEXT_PUBLIC_UPLOADTHING_URL
# ENV NEXT_PUBLIC_UPLOADTHING_URL=$NEXT_PUBLIC_UPLOADTHING_URL
# --------------------------------------------------------

# Build the Next.js application (ensure 'standalone' output is configured in next.config.js)
RUN npm run build

# Stage 3: Production image (using Next.js standalone output)
FROM node:18-alpine AS runner
WORKDIR /app

# Set NODE_ENV to production
ENV NODE_ENV production
# Optionally uncomment the line below to disable telemetry during runtime
# ENV NEXT_TELEMETRY_DISABLED 1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone Next.js server output
# Important: Ensure ownership is set for the non-root user
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy public assets
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Set the user to the non-root user
USER nextjs

# Expose the port the app runs on (default 3000 for Next.js)
EXPOSE 3000

# Set the host and port Next.js should bind to inside the container
ENV HOSTNAME="0.0.0.0"
ENV PORT 3000

# Command to run the application using the standalone server
# This command uses the server.js file generated by the standalone output mode
CMD ["node", "server.js"]